title: MohanKumar's First GitHub Page
author: Mohan Kumar
email: mohan153@yahoo.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my first GitHub page. Hopefully, and by god's grace, many more to continue.

# social links
twitter_username: your-twitter-handle
github_username:  MohanKumar153
show_excerpts: true # set to false to remove excerpts on the homepage
